# Generated by Django 4.2.13 on 2024-07-06 17:16

from django.db import migrations, models
import django.db.models.deletion
import django_recompi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField()),
            ],
            bases=(models.Model, django_recompi.models.RecomPIModelMixin),
        ),
        migrations.CreateModel(
            name="ReviewCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(db_index=True, max_length=200)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "One"),
                            ("2", "Two"),
                            ("3", "Three"),
                            ("4", "Four"),
                            ("5", "Five"),
                        ],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                (
                    "counter",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="testi.reviewcounter",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="testi.product",
                    ),
                ),
            ],
        ),
    ]
